//
//  MainViewController.swift
//  weather
//
//  Created by MIkkyMouse on 03.09.2020.
//  Copyright (c) 2020 Ivan Sosnovich. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit



class MainViewController: UIViewController {
    
    @IBOutlet var searchBar: UISearchBar!
    @IBOutlet var cityTable: UITableView!
    
    
    var citiesList = [CityData]()
    var citiesListFiltered = [CityData]()
    var searchActive = false
    
    
    override func viewDidLoad() {
        super.viewDidLoad()
        setup()
        
    }
    
}

// MARK: Setup
extension MainViewController {
    
    
    private func setup() {
        navigationItem.hidesBackButton = true
        cityTable.delegate = self
        cityTable.dataSource = self
        searchBar.placeholder = "Serach"
        searchBar.delegate = self
    }
    
}

// MARK: - setup UITableViewDataSource UITableViewDelegate
extension MainViewController: UITableViewDelegate, UITableViewDataSource {
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        if searchActive {
            return citiesListFiltered.count
        } else {
            return citiesList.count
        }
        
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCell(withIdentifier: "CityCell") as? CityCell
        if searchActive {
            cell?.setupCell(for: citiesListFiltered[indexPath.row])
            return cell!
        } else {
            cell?.setupCell(for: citiesList[indexPath.row])
            return cell!
        }
        
    }
    
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        let vc = WebViewController()
        vc.modalPresentationStyle = .formSheet
        vc.url = citiesList[indexPath.row].url
        self.present(vc, animated: true)
    }
    
}

// MARK: - Search Bar method
extension MainViewController: UISearchBarDelegate {
    
    
    func searchBarTextDidBeginEditing(_ searchBar: UISearchBar) {
        searchActive = true
    }
    
    func searchBarCancelButtonClicked(_ searchBar: UISearchBar) {
        searchActive = false
        searchBar.text = ""
        searchBar.resignFirstResponder()
        cityTable.reloadData()
    }
    
    func searchBar(_ searchBar: UISearchBar, textDidChange searchText: String) {
        
        citiesListFiltered = citiesList.filter({ (city: CityData) -> Bool in
            return city.name.lowercased().contains(searchText.lowercased())
        })
        
        cityTable.reloadData()
        
    }
    
    
}


